config/routes.rb
# typed: strict
# frozen_string_literal: true

require 'resque/server'
require 'resque/scheduler'
require 'resque/scheduler/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hashtags/index'

  resources :hashtags do
    resources :tweets
  end

  resources :tweets

  root 'hashtags#index'
  mount Resque::Server.new, at: "/resque"
end

app/models/application_record.rb
# typed: strong
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
# typed: false
# frozen_string_literal: true

# == Schema Information
#
# Table name: hashtags
#
#  id         :bigint           not null, primary key
#  hashtag    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Hashtag < ApplicationRecord
  validates_uniqueness_of :hashtag, if: :validate_query
  validates :hashtag, presence: true
  before_save :validate_query
  validate :validate_query

  def self.hashtags
    all.map(&:hashtag)
  end

  def validate_query
    cleaned = QueryMatchUtil.clean_query hashtag
    if cleaned
      self.hashtag = cleaned
    else
      errors.add(:hashtag, 'is not a well constructed query')
      false
    end
  end
end

app/models/tweet.rb
# typed: false
# frozen_string_literal: true

# == Schema Information
#
# Table name: tweets
#
#  id         :bigint           not null, primary key
#  name       :string
#  tweet_id   :string
#  date       :datetime
#  hashtag    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  content    :text
#

class Tweet < ApplicationRecord
  before_create :limit_table
  acts_as_paranoid
  validates_uniqueness_of :tweet_id, scope: :hashtag

  def self.get_full_content(status)
    content = if status.retweet?
                untrucate(status.retweeted_status)
              else
                untrucate(status)
              end
    content
  end

  def self.untrucate(status)
    if status.truncated? && status.attrs[:extended_tweet]
      status.attrs[:extended_tweet][:full_text]
    else
      status.attrs[:full_text] || status.attrs[:text]
    end
  end

  private

  def limit_table
    Tweet.first.destroy_fully! if Tweet.count >= 6000
  end
end

app/controllers/application_controller.rb
# typed: strong
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/hashtags_controller.rb
# typed: false
# frozen_string_literal: true

class HashtagsController < ApplicationController
  def index
    @hashtags = Hashtag.all
  end

  def new
    @hashtag = Hashtag.new
  end

  def show
    @hashtag = Hashtag.find(params[:id])
    @tweets = Tweet.where(hashtag: @hashtag.hashtag).order(date: :desc)
                   .paginate(page: params[:page], per_page: 20)
  end

  def destroy
    @hashtag = Hashtag.find(params[:id])
    @tweets = Tweet.where(hashtag: @hashtag.hashtag)
    @hashtag.destroy
    Resque.enqueue(DeleteTweetsJob, @hashtag.hashtag)
    redirect_to hashtags_path
  end

  def create
    @hashtag = Hashtag.new(hastag_params)
    if @hashtag.save
      TweetSearchJob.search_hashtag(@hashtag, 20)
      redirect_to @hashtag
    else
      render 'new'
    end
  end

  private

  def hastag_params
    params.require(:hashtag).permit(:hashtag)
  end
end

app/controllers/tweets_controller.rb
# typed: strong
# frozen_string_literal: true

class TweetsController < ApplicationController
end

app/helpers/application_helper.rb
# typed: strong
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/hashtags_helper.rb
# typed: strong
# frozen_string_literal: true

module HashtagsHelper
end

app/helpers/tweets_helper.rb
# typed: strong
# frozen_string_literal: true

module TweetsHelper
end

app/views/hashtags/_hashtag.html.erb
<div class="col-auto mb-4">
  <div class="card" style="width: 12rem";>
    <div class="card-body">
      <h2 class="text-truncate"><%= tag.hashtag %></h2>
      <%= link_to 'Show', hashtag_path(tag), id:"show_#{tag.hashtag}", class: "btn btn-secondary btn-sm" %>
      <%= link_to 'Delete', hashtag_path(tag), method: :delete,
	  data: { confirm: 'Are you sure?' }, id:"delete_#{tag.hashtag}", class: "btn btn-danger btn-sm" %>
    </div>
  </div>
</div>

app/views/hashtags/index.html.erb
<div class="row">
  <div class="container-fluid mt-4">
    <p>
      <%= link_to 'New hashtag', new_hashtag_path, class: "btn btn-primary" %>
    </p>
  </div>
</div>

<div class="row">

  <div class="container-fluid mt-4">
    <div class="row justify-content-between">
      <%= render partial: "hashtag", collection: @hashtags, as: 'tag' %>
    </div>
  </div>

</div>

app/views/hashtags/new.html.erb
<%= form_with scope: :hashtag, url: hashtags_path, local: true do |form| %>

<div class="container">
  <div class="row  justify-content-center">
    <div class="jumbotron" style="max-width: 25rem; max-height: 33rem;">
	<p>
	  Enter a hashtag (a string starting with #) or a combination of hashtags using
	  the operators OR and AND.
	</p>
	<p>
	  You can also use parentheses!
	</p>
	<p>
	  Examples: <br>
	  #cat; #cat AND #dog; #cat OR #dog; <br>
	  #cat AND #dog OR #bear. <br>
	</p>
	<p>
	  <small>
	    Notice: this query is left-associative, then: <br>
	    #cat OR #dog AND #duck &#8801; (#cat OR #dog) AND #duck
	  </small>
	</p>
	<div class="col-md-auto">
	  <div class="form-group">
	    <%= form.label :hashtag %><%= form.text_field :hashtag, class: "form-control"  %>
	  </div>

	<%= form.submit "Hunt Tweets", class: "btn btn-lg btn-primary btn-block" %>  
	</div>
    </div>
    <% end %>
  </div>

  <div class="row justify-content-center">
    <% if @hashtag.errors.any? %>
    <div id="error_explanation">
      <div class="container d-flex justify-content-center">
	<div class="jumbotron bg-warning text-dark">
	    <p>
	      <%= pluralize(@hashtag.errors.count, "error") %> prohibited
	      this hashtag from being hunted:
	    </p>
	    <ul>
	      <% @hashtag.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	      <% end %>
	    </ul>
	</div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<%= link_to 'Back', hashtags_path %>

app/views/hashtags/show.html.erb
<div  
  id="hashtag" 
  data-channel-subscribe="hashtag" 
  data-hashtag-id="<%= @hashtag.id %>">

  <div class="container">
    <div class="d-flex">
      <div class="p-2">
	<p>
	  <%= link_to 'Back to hashtags', hashtags_path %>
	</p>
      </div>
      <div class="ml-auto p-2">
	<div class="digg_pagination">
	  <%= will_paginate @tweets, :container => false %>
	</div>
      </div>
    </div>

    <p>
      <strong>Hashtag:</strong>
      <%= @hashtag.hashtag %>
    </p>
  </div>

  <div class="row">

    <div class="container-fluid">
      <div class="row justify-content-center" id="tweets-card">
	<%= render partial: "tweets/tweet", collection: @tweets %>
      </div>
    </div>

  </div>

  <div class="d-flex">
    <div class="p-2">
      <p>
	<%= link_to 'Back to hashtags', hashtags_path %>
      </p>
    </div>
    <div class="ml-auto p-2">
      <div class="digg_pagination">
	<%= will_paginate @tweets, :container => false %>
      </div>
    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweet Hunter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row  justify-content-center">
	<div class="page-header text-center">
	  <h1>Tweet Hunter</h1>
	  <p class="lead text-center">Where Tweets are Hunted by You</p>
	</div>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_tweet.html.erb
<div class="col-auto mb-4 mr-2">
  <div class="container" style="width: 21rem; max-height: 20rem;">
    <div class="card">
      <div class="card-body" id="tweet_id_<%= tweet.tweet_id %>" >
	<div class="row d-flex flex-row">
	  <div class="container d-flex justify-content-center">
	    <p class="card-text text-center"> <%= tweet.content %></p>
	  </div>
	</div>
	<div class="row d-flex">
	  <div class="container d-flex flex-row-reverse">
	    <footer class="blockquote-footer"> <%= tweet.name %> </footer>
	  </div>
	</div>
      </div>
      <div class="card-footer text-center text-muted">
	<footer > <%= tweet.date %> </footer>
      </div>
    </div>
  </div>
</div>